### ISSUE TITLE
Android V2 embedding

### ISSUE THREAD

**Issue by MirzaHimamiHanif** [kakzaki/blue_thermal_printer#106] opened 2021-10-14 06:51 UTC
The plugins `blue_thermal_printer` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

Can you upgrade this?

**Comment by fuadreza** [comment] 2022-04-06 06:20
already resolved in issue #96 on version 1.1.5

**Comment by kakzaki** [comment] 2022-08-25 08:55
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.

**Closed by kakzaki** 2022-08-25 08:55 UTC
